# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Headline' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'HandyJSON', '~> 4.2.0'
  pod 'Kingfisher'
  pod 'IBAnimatable'
  pod 'SwiftTheme'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SQLite.swift'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'SGPagingView','~> 1.3.7'
  pod 'BMPlayer'
  pod 'FDFullscreenPopGesture'
  pod 'lottie-ios'

end
